use_frameworks!
platform :ios, '10.0'

target 'RxRetroSwift_Example' do
  pod 'RxRetroSwift', :path => '../'
  
  target 'RxRetroSwift_Tests' do
    inherit! :search_paths
    
    pod 'Quick'
    pod 'RxNimble'
  end
end

