use_frameworks!

target 'RxRetroSwift_Example' do
  pod 'RxRetroSwift', :path => '../'

  target 'RxRetroSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
