use_frameworks!
platform :ios, '9.0'

target 'RxRetroSwift_Example' do
  pod 'RxRetroSwift', :path => '../'
  
  target 'RxRetroSwift_Tests' do
    inherit! :search_paths
    
    pod 'Quick', '~> 1.2.0'
    pod 'RxNimble', '~> 4.1.0'
  end
end

